apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  ray-dashboard.json: |
    {
      "dashboard": {
        "title": "Ray DSP Training",
        "panels": [
          {
            "title": "Reward Trend",
            "type": "graph",
            "targets": [
              {
                "expr": "ray_training_reward",
                "legendFormat": "Reward",
                "intervalFactor": 2
              }
            ]
          },
          {
            "title": "Synth Frequency",
            "type": "graph",
            "targets": [
              {
                "expr": "dsp_synth_frequency",
                "legendFormat": "Frequency (Hz)",
                "intervalFactor": 2
              }
            ]
          }
        ]
      }
    }
