apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ray-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ray-worker-mig
  minReplicas: 1  # Up to 1 Workers
  maxReplicas: 6  # Up to 6 Workers
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # If CPU usage exceeds 70%, add Worker
  - type: Resource
    resource:
      name: nvidia.com/gpu
      target:
        type: Utilization
        averageUtilization: 80  # If CPU usage exceeds 80%, add Worker
